app/user_login/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.dynlottonr.models import Lottoresults, Main, Super, User, Usertickets
from app.extensions.database import db, CRUDMixin
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user


blueprint = Blueprint('user_login', __name__)


@blueprint.get('/login')
def get_login():
    print('get login xxxDDD')
    return render_template('logsignup/login.html')


@blueprint.post('/login')
def post_login():
    print('logged in YYYYDDD')
    print(request.form)

    user = User.query.filter_by(mail=request.form['email']).first()

    if not user or not check_password_hash(user.password, request.form['password']):
        print('wrong email or password')
        return render_template('logsignup/login.html', error='Wrong email or password')
    else:
        print('success!')
        # reroute to other page.
    login_user(user)
    return redirect(url_for('ticket_form.get_tickets'))


@blueprint.get('/logout')
def logout():
    logout_user()
    print('log out successful')
    return redirect(url_for('user_login.get_login'))
# register ab hier


@blueprint.get('/register')
def get_register():
    print('get register xxxDDD')
    return render_template('logsignup/signup.html')


@blueprint.post('/register')
def post_register():
    print(request.form)

    new_user = User(
        name=request.form['username'],
        mail=request.form['email'],
        password=generate_password_hash(request.form.get('password')))

    # check if user already exists
    user = User.query.filter_by(mail=request.form['email']).first()
    if user:
        print('user already exists')
        # make alert that user exists already
        return render_template('logsignup/signup.html', error='The email address is already registered.')

    else:
        new_user.save()
        print('success!')

        login_user(new_user)
        return redirect(url_for('ticket_form.get_tickets'))

app/templates/logsignup/login.html
{% extends 'simple_pages/base.html' %} {% block title %}Login{% endblock %} {%
block head %} {{ super() }}
<link
  href="{{ url_for('static', filename='css/login.css') }}"
  rel="stylesheet"
/>
{% endblock %} {% block body %}
<div class="login-screen">
  <p style="color: tomato">{{ error }}</p>
  <div class="app-title">
    <img
      class="logo2"
      src="https://drive.google.com/uc?export=view&id=1EfrjITRzCrElKJ7nnQ34dKFBI036mR0F"
    />
    <h1>Log in</h1>
  </div>
  <div class="login-form">
    <form action="" method="post">
      <div class="control-group">
        <input
          type="text"
          class="login-field"
          name="email"
          placeholder="Email"
          id="login-name"
          required
        />
        <label class="login-field-icon fui-user" for="login-name"></label>
      </div>
      <div class="control-group">
        <input
          type="password"
          class="login-field"
          name="password"
          placeholder="Password"
          id="login-pass"
          required
        />
        <label class="" for=""></label>
      </div>
      <div class="link">
        <a class="register" href="{{ url_for('user_login.get_register') }}"
          >Register</a
        >
        <button type="submit" class="login">Log in</button>
      </div>
    </form>
  </div>
</div>
{%endblock%}

app/templates/logsignup/signup.html
{% extends 'simple_pages/base.html' %} {% block title %}Login{% endblock %} {%
block head %} {{ super() }}
<link
  href="{{ url_for('static', filename='css/login.css') }}"
  rel="stylesheet"
/>
{% endblock %} {% block body %}

<div class="login-screen">
  <p style="color: tomato">{{ error }}</p>
  <div class="app-title">
    <img
      class="logo2"
      src="https://drive.google.com/uc?export=view&id=1EfrjITRzCrElKJ7nnQ34dKFBI036mR0F"
    />
    <h1>Sign up</h1>
  </div>
  <div class="login-form">
    <form action="" method="post">
      <div class="control-group">
        <input
          type="text"
          class="login-field"
          name="username"
          placeholder="Username"
          id="login-username"
          required
        />
        <label class="login-field-icon fui-user" for="login-username"></label>
      </div>
      <div class="control-group">
        <input
          type="text"
          class="login-field"
          name="email"
          placeholder="Email"
          id="login-email"
          required
        />
        <label class="login-field-icon fui-user" for="login-email"></label>
      </div>
      <div class="control-group">
        <input
          type="password"
          class="login-field"
          name="password"
          placeholder="Password"
          id="login-pass"
          required
        />
        <label class="" for=""></label>
      </div>
      <div class="link">
        <button type="submit" class="login">Register</button>
      </div>
    </form>
  </div>
</div>
{% if error %} {% endif %} {%endblock%}