app/dynlottonr/routes.py
from .models import Lottoresults, Main, Super
from flask import Blueprint, render_template, request, current_app, redirect, url_for
from app.simple_pages import routes


blueprint = Blueprint('eurojackpot', __name__)


# jinja templating first example
@blueprint.route('/eurojackpot')
def lotto():
    page_number = request.args.get('page', 1, type=int)
    # import von config klappt nicht.
    per_page = current_app.config.get('LOTTODAYS_PER_PAGE', 3)
    # lottonr = Lottoresults.query.all()
    lottonr_paginated = Lottoresults.query.paginate(
        page=page_number, per_page=per_page)
    return render_template('lottonum/eurojackpot.html', lottonr_paginated=lottonr_paginated)


# das klappt aber nicht innerhalb eine page...
@blueprint.route('/eurojackpot/<day>')
def eurojackpot(day):
    dayresult = Lottoresults.query.filter_by(day=day).first_or_404()
    mainres = Main.query.filter_by(id=dayresult.mainnr_id).first()

    superres = Super.query.filter_by(id=dayresult.supernr_id).first()
    return render_template(
        'lottonum/eurojackpotresult.html',
        mainnr=[mainres.nr1, mainres.nr2,
                mainres.nr3, mainres.nr4, mainres.nr5],
        supernr=[superres.nr1, superres.nr2],
        day=dayresult.day
    )


# store data in db.
@blueprint.route('/run-seed')
def run_seed():
    if not Lottoresults.query.filter_by(day='monday').first():
        import app.scripts.seeds
        print('stored data to db')
        return 'Database seed completed!'
    else:
        print('already in db')
        return redirect(url_for('simple_pages.landingpage'))

app/simple_pages/__init__.py
from . import routes

app/simple_pages/routes.py
from flask import Blueprint, render_template
blueprint = Blueprint('simple_pages', __name__)


@blueprint.route('/')
def landingpage():
    return render_template('simple_pages/home.html')


@blueprint.route('/about')
def about():
    return render_template('simple_pages/about.html')

app/user_login/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.dynlottonr.models import Lottoresults, Main, Super, User, Usertickets
from app.extensions.database import db, CRUDMixin
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user


blueprint = Blueprint('user_login', __name__)


@blueprint.get('/login')
def get_login():
    print('get login xxxDDD')
    return render_template('logsignup/login.html')


@blueprint.post('/login')
def post_login():
    print('logged in YYYYDDD')
    print(request.form)

    user = User.query.filter_by(mail=request.form['email']).first()

    if not user or not check_password_hash(user.password, request.form['password']):
        print('wrong email or password')
        return render_template('logsignup/login.html', error='Wrong email or password')
    else:
        print('success!')
        # reroute to other page.
    login_user(user)
    return redirect(url_for('ticket_form.get_tickets'))


@blueprint.get('/logout')
def logout():
    logout_user()
    print('log out successful')
    return redirect(url_for('user_login.get_login'))
# register ab hier


@blueprint.get('/register')
def get_register():
    print('get register xxxDDD')
    return render_template('logsignup/signup.html')


@blueprint.post('/register')
def post_register():
    print(request.form)

    new_user = User(
        name=request.form['username'],
        mail=request.form['email'],
        password=generate_password_hash(request.form.get('password')))

    # check if user already exists
    user = User.query.filter_by(mail=request.form['email']).first()
    if user:
        print('user already exists')
        # make alert that user exists already
        return render_template('logsignup/signup.html', error='The email address is already registered.')

    else:
        new_user.save()
        print('success!')

        login_user(new_user)
        return redirect(url_for('ticket_form.get_tickets'))

app/templates/simple_pages/about.html
{% extends 'simple_pages/base.html' %}

{% block title %}About{% endblock %}
{% block head %}
  {{ super() }}
  <link href="{{ url_for('static', filename='css/about.css') }}" rel="stylesheet" />
{% endblock %}

{% block body %}
 <h2>About Us</h2>
    <p class="p1">This is the about us page</p>
    <div class="gridd">
      <div class="testclass">
        <h3>Hello</h3>
        <p>
          here are many variations of passages of Lorem Ipsum available, but the
          majority have suffered alteration in some form, by injected humour, or
          randomised words which don't look even slightly believable. If you are
          going to use a passage of Lorem Ipsum, you need to be sure there isn't
          anything embarrassing hidden in the middle of text. All the Lorem
          Ipsum generators on the Internet tend to repeat predefined chunks as
          necessary, making this the first true generator on the Internet. It
          uses a dictionary of over 200 Latin words, combined with a handful of
          model sentence structures, to generate Lorem Ipsum which looks
          reasonable. The generated Lorem Ipsum is therefore always free f
        </p>
      </div>
      <div class="testclass">
        <h3>Hello</h3>
        <p>
          Hhere are many variations of passages of Lorem Ipsum available, but
          the majority have suffered alteration in some form, by injected
          humour, or randomised words which don't look even slightly believable.
          If you are going to use a passage of Lorem Ipsum, you need to be sure
          there isn't anything embarrassing hidden in the middle of text. All
          the Lorem Ipsum generators on the Internet tend to repeat predefined
          chunks as necessary, making this the first true generator on the
          Internet. It uses a dictionary of over 200 Latin words, combined with
          a handful of model sentence structures, to generate Lorem Ipsum which
          looks reasonable. The generated Lorem Ipsum is therefore always free f
        </p>
      </div>
      <div class="testclass">
        <h3>This is test otme demonstrat</h3>
        <p>
          here are many variations of passages of Lorem Ipsum available, but the
          majority have suffered alteration in some form, by injected humour, or
          randomised words which don't look even slightly believable. If you are
          going to use a passage of Lorem Ipsum, you need to be sure there isn't
          anything embarrassing hidden in the middle of text. All the Lorem
          Ipsum generators on the Internet tend to repeat predefined chunks as
          necessary, making this the first true generator on the Internet. It
          uses a dictionary of over 200 Latin words, combined with a handful of
          model sentence structures, to generate Lorem Ipsum which looks
          reasonable. The generated Lorem Ipsum is therefore always free f
        </p>
      </div>
    </div>

{% endblock %}

app/templates/simple_pages/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    <title>{%block title%}{%endblock%}</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="{{ url_for('static', filename='css/base.css') }}"
      rel="stylesheet"
    />
    <link href="FoundationsHandIns/JS/burger.js" />
    {% endblock %}
  </head>
  <body>
    <header>
      <nav class="navbar">
        <a class="brand" href="{{ url_for('simple_pages.landingpage') }}">24</a>
        <ul class="navmenu">
          <li class="navitem">
            <a class="navlink" href="{{ url_for('simple_pages.about') }}"
              >About</a
            >
          </li>
          <li class="navitem">
            <a class="navlink" href="{{ url_for('eurojackpot.lotto') }}"
              >Eurojackpot</a
            >
          </li>
          <li class="navitem">
            <a class="navlink" href="{{ url_for('ticket_form.get_tickets') }}"
              >Tickets</a
            >

            <!-- get_tickets! -->
          </li>
          <li class="navitem">
            <a class="navlink" href="{{ url_for('user_login.get_login') }}"
              >Log in</a
            >
          </li>
          <!-- logic log in log out. -->
        </ul>

        <div class="hamburger">
          <span class="bar"></span>
          <span class="bar"></span>
          <span class="bar"></span>
        </div>
      </nav>
    </header>
    {% block body %} {% endblock %}
    <footer style="text-align: center; font-size: 1.2em">
      <hr />
      {% if current_user.is_authenticated %}
      <small>
        Logged in as {{current_user.mail}}
        <a href="{{ url_for('user_login.logout') }}">Logout</a>
      </small>
      {% endif %}
    </footer>
  </body>
  <script src="{{ url_for('static', filename='burger.js') }}"></script>
</html>

app/templates/simple_pages/home.html
{% extends 'simple_pages/base.html' %} {% block title %}HOME{% endblock %} {%
block head %} {{ super() }}
<link
  href="{{ url_for('static', filename='css/home.css') }}"
  rel="stylesheet"
/>
{% endblock %} {% block body %}

<h1>Welcome to 24.</h1>
<h2>You place to store your lottery tickets or generate your own.</h2>
<div class="langrid">
  <div class="lottotext">
    <h3>Generate your own lottery ticket</h3>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
      voluptates, quod, quia, voluptate quae voluptatem quibusdam voluptatum
      quos quidem quas nesciunt. Quisquam, quae. Quisquam voluptates, quod,
      quia, voluptate quae voluptatem quibusdam voluptatum quos quidem quas
      nesciunt. Quisquam, quae.
    </p>
  </div>
  <div class="lanbox">
    <h3>Store your lottery ticket</h3>
    <img
      class="lottoimg"
      src="https://www.augsburger-allgemeine.de/img/bayern/crop63425816/4296423656-cv16_9-w1200/Lotto.jpg"
      alt="lottobackground"
    />
  </div>
</div>
<div class="YT">
  <h4>Watch our YT</h4>
  <iframe
    class="ytframe"
    src="https://www.youtube.com/embed/vaU8BAoVIj8?autoplay=1&mute=1"
  >
  </iframe>
</div>
{% endblock %}