app/dynlottonr/routes.py
from .models import Lottoresults, Main, Super
from flask import Blueprint, render_template, request, current_app, redirect, url_for
from app.simple_pages import routes


blueprint = Blueprint('eurojackpot', __name__)


# jinja templating first example
@blueprint.route('/eurojackpot')
def lotto():
    page_number = request.args.get('page', 1, type=int)
    # import von config klappt nicht.
    per_page = current_app.config.get('LOTTODAYS_PER_PAGE', 3)
    # lottonr = Lottoresults.query.all()
    lottonr_paginated = Lottoresults.query.paginate(
        page=page_number, per_page=per_page)
    return render_template('lottonum/eurojackpot.html', lottonr_paginated=lottonr_paginated)


# das klappt aber nicht innerhalb eine page...
@blueprint.route('/eurojackpot/<day>')
def eurojackpot(day):
    dayresult = Lottoresults.query.filter_by(day=day).first_or_404()
    mainres = Main.query.filter_by(id=dayresult.mainnr_id).first()

    superres = Super.query.filter_by(id=dayresult.supernr_id).first()
    return render_template(
        'lottonum/eurojackpotresult.html',
        mainnr=[mainres.nr1, mainres.nr2,
                mainres.nr3, mainres.nr4, mainres.nr5],
        supernr=[superres.nr1, superres.nr2],
        day=dayresult.day
    )


# store data in db.
@blueprint.route('/run-seed')
def run_seed():
    if not Lottoresults.query.filter_by(day='monday').first():
        import app.scripts.seeds
        print('stored data to db')
        return 'Database seed completed!'
    else:
        print('already in db')
        return redirect(url_for('simple_pages.landingpage'))

app/templates/lottonum/eurojackpot.html
{% extends 'simple_pages/base.html' %} {% block title %}EUROJACKPOT{% endblock
%} {% block head %} {{ super() }}
<link
  href="{{ url_for('static', filename='css/eurojackpot.css') }}"
  rel="stylesheet"
/>
{% endblock %} {% block body %}

<h1>Results by day</h1>
{% for lotto in lottonr_paginated %}
<!-- klappt nur ohhne .items.. -->
<div class="test">
  <h2>{{lotto.day.capitalize()}}</h2>
  <a class="links" href="{{url_for('eurojackpot.eurojackpot', day=lotto.day)}}"
    >{{lotto.day.capitalize()}}</a
  >
  {% endfor %}
</div>
<div class="pageselector">
  {% if lottonr_paginated.prev_num %}
  <a href="/eurojackpot?page={{ lottonr_paginated.prev_num }}">Previous Page</a>
  {% else %}
  <span>Previous Page</span>
  {% endif %}

  <span> - </span>

  {% if lottonr_paginated.next_num %}
  <a href="/eurojackpot?page={{ lottonr_paginated.next_num }}">Next Page</a>
  {% else %}
  <span>Next Page</span>
  {% endif %}
</div>

{% endblock %}

app/templates/lottonum/eurojackpotresult.html
{% extends 'simple_pages/base.html' %} {% block title %}RESULT{% endblock %} 

{% block head %}
  {{ super() }}
  <link href="{{ url_for('static', filename='css/eurojackpotresult.css') }}" rel="stylesheet" />
  
  
{% endblock %}

{%block body%}

<h1>RESULT:{{(day).capitalize()}}</h1>


<h1>MAIN NUMBERS:{{mainnr}}</h1>

<h1>SUPER NUMBERS:{{supernr}}</h1>

{% endblock %}